# Generated by Django 3.1.4 on 2020-12-07 14:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='License plate of the vehicle.', max_length=30, verbose_name='License Plate')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Plate creation date.')),
            ],
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=3, help_text='The level of discontent. From 1 to 5.', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Anger Level')),
                ('description', models.TextField(blank=True, help_text='The reason of the grievance.', max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Grievance creation date.')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plate')),
            ],
        ),
    ]
