# Generated by Django 3.1.4 on 2020-12-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201209_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='country',
            field=models.CharField(choices=[('ru', 'ru'), ('am', 'am'), ('by', 'by'), ('ua', 'ua')], default='Ru', help_text='Страна', max_length=20, verbose_name='Страна'),
        ),
    ]
