# Generated by Django 3.1.4 on 2020-12-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201210_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='description',
            field=models.TextField(blank=True, help_text='Описание ситуации', max_length=300, null=True, verbose_name='Описание'),
        ),
    ]
