# Generated by Django 3.1.4 on 2021-01-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210111_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='description',
            field=models.TextField(blank=True, help_text='Описание ситуации', max_length=2000, null=True, verbose_name='Описание'),
        ),
    ]
