# Generated by Django 3.1.4 on 2021-05-26 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210126_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='email',
            field=models.CharField(blank=True, help_text='Email for result', max_length=60, null=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='gibdd_code',
            field=models.CharField(blank=True, help_text='Code from GIBDD site to check status', max_length=120, null=True, verbose_name='GIBDD code'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='gibdd_id',
            field=models.CharField(blank=True, help_text='Grievance ID from GIBDD site', max_length=30, null=True, verbose_name='GIBDD ID'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='gibdd_link',
            field=models.CharField(blank=True, help_text='Link to grievance to GIBDD site', max_length=200, null=True, verbose_name='GIBDD link'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='result',
            field=models.CharField(blank=True, help_text='Result of grievance', max_length=2000, null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='level',
            field=models.PositiveSmallIntegerField(default=3, help_text='The level of discontent from 1 to 5, where 5 is very angry!', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Уровень недовольства'),
        ),
    ]
