# Generated by Django 3.1.4 on 2021-08-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210526_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('fullname', models.CharField(blank=True, max_length=128, null=True)),
                ('symbol', models.CharField(blank=True, max_length=128, null=True)),
                ('current_price', models.DecimalField(decimal_places=20, default=0, max_digits=30)),
                ('highest_price', models.DecimalField(decimal_places=20, default=0, max_digits=30)),
                ('highest_date', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(max_length=512)),
            ],
        ),
    ]
