# Generated by Django 3.1.4 on 2021-08-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_crypto_limit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='current_price',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='highest_price',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='limit_price',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
    ]
